<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 Summary Statistics and Graphing | Introduction to Statistical Methodology, Second Edition</title>
  <meta name="description" content="Chapter 1 Summary Statistics and Graphing | Introduction to Statistical Methodology, Second Edition" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 Summary Statistics and Graphing | Introduction to Statistical Methodology, Second Edition" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="dereksonderegger/570_II" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 Summary Statistics and Graphing | Introduction to Statistical Methodology, Second Edition" />
  
  
  

<meta name="author" content="Derek L. Sonderegger &amp; Robert Buscaglia" />


<meta name="date" content="2019-08-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html"><i class="fa fa-check"></i><b>1</b> Summary Statistics and Graphing</a><ul>
<li class="chapter" data-level="1.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#variable-types"><i class="fa fa-check"></i><b>1.1</b> Variable Types</a><ul>
<li class="chapter" data-level="1.1.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#categorical"><i class="fa fa-check"></i><b>1.1.1</b> Categorical</a></li>
<li class="chapter" data-level="1.1.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#numerical"><i class="fa fa-check"></i><b>1.1.2</b> Numerical</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#randomization-and-sampling"><i class="fa fa-check"></i><b>1.2</b> Randomization and Sampling</a><ul>
<li class="chapter" data-level="1.2.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#sample-techniques"><i class="fa fa-check"></i><b>1.2.1</b> Sample Techniques</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#graphical-summaries"><i class="fa fa-check"></i><b>1.3</b> Graphical Summaries</a><ul>
<li class="chapter" data-level="1.3.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#univariate---categorical"><i class="fa fa-check"></i><b>1.3.1</b> Univariate - Categorical</a></li>
<li class="chapter" data-level="1.3.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#univariate---continuous"><i class="fa fa-check"></i><b>1.3.2</b> Univariate - Continuous</a></li>
<li class="chapter" data-level="1.3.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#bivariate---categorical-vs-continuous"><i class="fa fa-check"></i><b>1.3.3</b> Bivariate - Categorical vs Continuous</a></li>
<li class="chapter" data-level="1.3.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#bivariate---continuous-vs-continuous"><i class="fa fa-check"></i><b>1.3.4</b> Bivariate - Continuous vs Continuous</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#measures-of-centrality"><i class="fa fa-check"></i><b>1.4</b> Measures of Centrality</a><ul>
<li class="chapter" data-level="1.4.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#mean"><i class="fa fa-check"></i><b>1.4.1</b> Mean</a></li>
<li class="chapter" data-level="1.4.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#median"><i class="fa fa-check"></i><b>1.4.2</b> Median</a></li>
<li class="chapter" data-level="1.4.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#mode"><i class="fa fa-check"></i><b>1.4.3</b> Mode</a></li>
<li class="chapter" data-level="1.4.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#examples"><i class="fa fa-check"></i><b>1.4.4</b> Examples</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#measures-of-spread"><i class="fa fa-check"></i><b>1.5</b> Measures of Spread</a><ul>
<li class="chapter" data-level="1.5.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#range"><i class="fa fa-check"></i><b>1.5.1</b> Range</a></li>
<li class="chapter" data-level="1.5.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#inter-quartile-range"><i class="fa fa-check"></i><b>1.5.2</b> Inter-Quartile Range</a></li>
<li class="chapter" data-level="1.5.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#variance"><i class="fa fa-check"></i><b>1.5.3</b> Variance</a></li>
<li class="chapter" data-level="1.5.4" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#standard-deviation"><i class="fa fa-check"></i><b>1.5.4</b> Standard Deviation</a></li>
<li class="chapter" data-level="1.5.5" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#coefficient-of-variation"><i class="fa fa-check"></i><b>1.5.5</b> Coefficient of Variation</a></li>
<li class="chapter" data-level="1.5.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#empirical-rule-of-thumb"><i class="fa fa-check"></i><b>1.5.6</b> Empirical Rule of Thumb</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#shape"><i class="fa fa-check"></i><b>1.6</b> Shape</a><ul>
<li class="chapter" data-level="1.6.1" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#symmetry"><i class="fa fa-check"></i><b>1.6.1</b> Symmetry</a></li>
<li class="chapter" data-level="1.6.2" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#unimodal-or-multi-modal"><i class="fa fa-check"></i><b>1.6.2</b> Unimodal or Multi-modal</a></li>
<li class="chapter" data-level="1.6.3" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#skew"><i class="fa fa-check"></i><b>1.6.3</b> Skew</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="1-summary-statistics-and-graphing.html"><a href="1-summary-statistics-and-graphing.html#exercises"><i class="fa fa-check"></i><b>1.7</b> Exercises</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Statistical Methodology, Second Edition</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="summary-statistics-and-graphing" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Summary Statistics and Graphing</h1>
<p>When confronted with a large amount of data, we seek to summarize the data into statistics that capture the essence of the data with as few numbers as possible. Graphing the data has a similar goal: to reduce the data to an image that represents all the key aspects of the raw data. In short, we seek to simplify the data in order to understand the trends while not obscuring important structure.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Every chapter, we will load all the librarys we will use at the beginning</span>
<span class="co"># of the chapter. These commands will start most every homework assignment</span>
<span class="co"># for this class, and likely, every R script you write.</span>
<span class="kw">library</span>(ggplot2)    <span class="co"># graphing functions</span>
<span class="kw">library</span>(dplyr)      <span class="co"># data summary tools</span>

<span class="co"># Set default behavior of ggplot2 graphs to be black/white theme</span>
<span class="kw">theme_set</span>(<span class="kw">theme_bw</span>())</code></pre></div>
<p>For this chapter, we will consider data from a the 2005 Cherry Blossom 10 mile run that occurs in Washington DC. This data set has 8636 observations that includes the runners state of residence, official time (gun to finish, in seconds), net time (start line to finish, in seconds), age, and gender of the runners.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(TenMileRace, <span class="dt">package=</span><span class="st">&#39;mosaicData&#39;</span>)
<span class="kw">head</span>(TenMileRace)   <span class="co"># examine the first few rows of the data</span></code></pre></div>
<pre><code>##   state time  net age sex
## 1    VA 6060 5978  12   M
## 2    MD 4515 4457  13   M
## 3    VA 5026 4928  13   M
## 4    MD 4229 4229  14   M
## 5    MD 5293 5076  14   M
## 6    VA 6234 5968  14   M</code></pre>
<div id="variable-types" class="section level2">
<h2><span class="header-section-number">1.1</span> Variable Types</h2>
<p>We will always want to be aware of the variable types in which we are working. We will distinguish variables into two principal categories: numerical and categorical.</p>
<div id="categorical" class="section level3">
<h3><span class="header-section-number">1.1.1</span> Categorical</h3>
<ul>
<li><strong>Categorical variables</strong> are variables whose elements take on non-numerical entries.</li>
</ul>
<p>Examples within the TenMileRace set include the <em>state</em> and <em>sex</em> variables. Categorical variables are typically unordered, such that if we chose to order ‘NM’ before ‘AZ’ in an evaluation of the <em>state</em> variable, there would be no impact on our analysis. Categorical variables that have an implied order are termed <strong>ordinal</strong> variables. Examples include the common A, B, C, D, F grade-scale system. The variable entries are non-numerical, but there is an implied order that A &gt; B &gt; C &gt; D &gt; F. Such an ordering could influence the way the data is evaluated.</p>
</div>
<div id="numerical" class="section level3">
<h3><span class="header-section-number">1.1.2</span> Numerical</h3>
<p><strong>Numerical variables</strong> are broadly classified as variables with numerical elements. Numerical variables within the TenMileRace set include the <em>time</em>, <em>net</em>, and <em>age</em> variables. Numerical variables are sub-classified as either discrete or continuous.</p>
<ul>
<li><strong>Discrete variables</strong> have entries that can be written as a list.</li>
</ul>
<p>Data that is discrete can take on a countable number of entries, such the variable <em>age</em> in years. We could write a list of numbers, <code>{0, 1, 2, ..., 122}</code><a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>, of which all values within the <em>age</em> variable could be drawn. Discrete variables are potentially finite, such as in the previous list for possible values of <em>age</em>. Additional examples include the number of students in a classroom or the number of offspring for a rabbit. Finite variables have important distributions such as the Binomial distribution. Discrete variables can also take on a potentially infinite number of possible values, but the values can still be listed, <code>{0, 1, 2, ...}</code>. Although there is no largest value within the list, the number of potential entries is still countable. Infinite valued discrete variables will also serve the basis for important distributions, such as the Poisson distribution.</p>
<ul>
<li><strong>Continuous variables</strong> have entries that take on numerical values that lie on an interval.</li>
</ul>
<p>To decided if a data attribute is discrete or continuous, I often as “Does a fraction of a value make sense?” If so, then the data is continuous. The variables <em>time</em> and <em>net</em> are both recorded in seconds, and in this case seem to conform to discrete. However, if we had instead recorded the minutes with fractions of a minute present, such as 75.25 minutes instead of 4515 seconds, we might realize these variables are more likely to be considered continuous. Continuous variables constitute a large set of distributions that will be studied, the most commonly known being the Normal distribution. For the Normal distribution, it is possible to see values ranging from <span class="math inline">\((-\infty, \infty)\)</span>. This constitutes an interval, albeit a very large interval. Thus, elements of the variables lie on an interval, and it is not possible to list out all possible entries. Another simple example will be the Uniform distribution, whose entries lie on the interval <code>(a,b)</code>, where <code>a</code> and <code>b</code> are any real valued number. Again, all potential observation of the variable can be found in the interval, but it is not possible to list out all possible outcomes.</p>
</div>
</div>
<div id="randomization-and-sampling" class="section level2">
<h2><span class="header-section-number">1.2</span> Randomization and Sampling</h2>
<p>An important aspect of working within statistics is the concept that the data we are working with has been collected randomly. We think of having a <strong>population</strong>, the collection of all possible observations under consideration. The population will be dependent on the problem at hand. In the case of performing a study at a university, it may be that the entire university is the population. However, you may be working with only a specific subject, in which case the population may be only Mathematics majors. A <strong>sample</strong> is a subset of the population for which information is gathered. From the university example, we may choose to collect information from 1,000 students (our sample) which is drawn from the entire university population of 30,000 students (our population).</p>
<p>The way we select our samples is done to ensure that we have randomly collected the data, such that there is no influence of correlation between samples interfering with our analysis. We will cover three broad sampling techniques that help ensure randomization of the samples collected.</p>
<div id="sample-techniques" class="section level3">
<h3><span class="header-section-number">1.2.1</span> Sample Techniques</h3>
<ul>
<li><strong>Simple Random Sampling (SRS)</strong> is when every member of the population is equally-likely to be chosen.</li>
</ul>
<p>For SRS to be used, we also ensure that every member of the population is selected independently. Let us take the a university of having 30,000 students enrolled to be our population of which we would like to selected 1,000 as a sample. To use SRS, we would assign every member of the population a value <code>{1, 2, ..., 30,000}</code> and then draw numbers, without replacement, from our list of values. Such random numbers can be drawn using a random number generator, or traditionally through the use of a random number table. Using this method would ensure that we obtain a random sampling drawn from the entire university. What we cannot do is draw a student, then also draw all of their siblings. If we were to use such a method, we would be introducing correlation within our samples. We must ensure that the students are all drawn randomly and that the selection is done independently.</p>
<ul>
<li><strong>Random Cluster Sampling</strong> draws entire clusters based on a division of the population.</li>
</ul>
</div>
</div>
<div id="graphical-summaries" class="section level2">
<h2><span class="header-section-number">1.3</span> Graphical Summaries</h2>
<div id="univariate---categorical" class="section level3">
<h3><span class="header-section-number">1.3.1</span> Univariate - Categorical</h3>
<p>If we have univariate data about a number of groups, often the best way to display it is using barplots. They have the advantage over pie-charts that groups are easily compared.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>sex)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>()</code></pre></div>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>One thing that can be misleading is if the zero on the y-axis is removed. In the following graph it looks like there are twice as many female runners as male until you examine the y-axis closely. In general, the following is a very misleading graph.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>sex)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_cartesian</span>(<span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">4300</span>, <span class="dv">4330</span>))</code></pre></div>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="univariate---continuous" class="section level3">
<h3><span class="header-section-number">1.3.2</span> Univariate - Continuous</h3>
<p>A histogram looks very similar to a bar plot, but is used to represent continuous data instead of categorical and therefore the bars will actually be touching.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>net)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>()</code></pre></div>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Often when a histogram is presented, the y-axis is labeled as “frequency” or “count” which is the number of observations that fall within a particular bin. However, it is often desirable to scale the y-axis so that if we were to sum up the area <span class="math inline">\((height * width)\)</span> then the total area would sum to 1. The re-scaling that accomplishes this is <span class="math display">\[density=\frac{\#\;observations\;in\;bin}{total\;number\;observations}\cdot\frac{1}{bin\;width}\]</span></p>
</div>
<div id="bivariate---categorical-vs-continuous" class="section level3">
<h3><span class="header-section-number">1.3.3</span> Bivariate - Categorical vs Continuous</h3>
<p>We often wish to compare response levels from two or more groups of interest. To do this, we often use side-by-side boxplots. Notice that each observation is associated with a continuous response value and a categorical value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>sex, <span class="dt">y=</span>net)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>In this graph, the edges of the box are defined by the 25% and 75% percentiles. That is to say, 25% of the data is to the below of the box, 50% of the data is in the box, and the final 25% of the data is to the above of the box. The line in the center of the box represents the 50% percentile. The dots are data points that traditionally considered outliers. We will define the Inter-Quartile Range (IQR) as the length of the box. It is conventional to define any observation more than 1.5*IQR from the box as an considered an outlier. In the above graph it is easy to see that the median time for the males is lower than for females, but the box width (one measure of the spread of the data) is approximately the same.</p>
<p>Because boxplots simplify the distribution to just 5 numbers, looking at side-by-side histograms might give similar information.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>net)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_grid</span>( . <span class="op">~</span><span class="st"> </span>sex )  <span class="co"># side-by-side plots based on sex</span></code></pre></div>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Orientation of graphs can certainly matter. In this case, it makes sense to stack the two graphs to facilitate comparisons in where the centers are and it is more obvious that the center of the female distribution is about 500 to 600 seconds higher than then center of the male distribution.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>net)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">facet_grid</span>( sex <span class="op">~</span><span class="st"> </span>. )  <span class="co"># side-by-side plots based on sex</span></code></pre></div>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="bivariate---continuous-vs-continuous" class="section level3">
<h3><span class="header-section-number">1.3.4</span> Bivariate - Continuous vs Continuous</h3>
<p>Finally we might want to examine the relationship between two continuous random variables. For example, we might wish to explore the relationship between a runners age and their net time.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(TenMileRace, <span class="kw">aes</span>(<span class="dt">x=</span>age, <span class="dt">y=</span>net, <span class="dt">color=</span>sex)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
</div>
<div id="measures-of-centrality" class="section level2">
<h2><span class="header-section-number">1.4</span> Measures of Centrality</h2>
<p>The most basic question to ask of any dataset is ‘What is the typical value?’ There are several ways to answer that question and they should be familiar to most students.</p>
<div id="mean" class="section level3">
<h3><span class="header-section-number">1.4.1</span> Mean</h3>
<p>Often called the average, or arithmetic mean, we will denote this special statistic with a bar. We define <span class="math display">\[\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_{i}=\frac{1}{n}\left(x_{1}+x_{2}+\dots+x_{n}\right)\]</span></p>
<p>If we want to find the mean of five numbers <span class="math inline">\(\left\{ 3,6,4,8,2\right\}\)</span> the calculation is <span class="math display">\[\bar{x}   =   \frac{1}{5}\left(3+6+4+8+2\right)
    =   \frac{1}{5}\left(23\right)
    =   23/5
    =   4.6\]</span></p>
<p>This can easily be calculated in R by using the function <code>mean()</code>. We first extract the column we are interested in using the notation: <code>DataSet$ColumnName</code> where the $ signifies grabbing the column.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># TenMileRace$net  is the set of data to calculate the mean of. </span>
<span class="kw">mean</span>( TenMileRace<span class="op">$</span>net ) <span class="co"># Simplest way of doing this calculation</span></code></pre></div>
<pre><code>## [1] 5599.065</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Using the dplyr package we first specify the data set </span>
<span class="co"># Then specify we wish to summarize() the data set</span>
<span class="co"># The summary we want to do is to calculate the mean of the &#39;net&#39; column.</span>
<span class="co"># and we want to name what we are about to create as Calculated.Mean</span>
TenMileRace <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">Calculated.Mean =</span> <span class="kw">mean</span>(net) )  </code></pre></div>
<pre><code>##   Calculated.Mean
## 1        5599.065</code></pre>
</div>
<div id="median" class="section level3">
<h3><span class="header-section-number">1.4.2</span> Median</h3>
<p>If the data were to be ordered, the median would be the middle most observation (or, in the case that <span class="math inline">\(n\)</span> is even, the mean of the two middle most values).</p>
<p>In our simple case of five observations <span class="math inline">\(\left\{ 3,6,4,8,2\right\}\)</span>, we first sort the data into <span class="math inline">\(\left\{ 2,3,4,6,8\right\}\)</span> and then the middle observation is clearly <span class="math inline">\(4\)</span>.</p>
<p>In R the median is easily calculated by the function <code>median()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Use the median() function to calculate the median for us.</span>
<span class="co"># median( TenMileRace$net )</span>
TenMileRace <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">Median =</span> <span class="kw">median</span>(net) ) </code></pre></div>
<pre><code>##   Median
## 1   5555</code></pre>
</div>
<div id="mode" class="section level3">
<h3><span class="header-section-number">1.4.3</span> Mode</h3>
<p>This is peak in the distribution. A distribution might have a single peak or multiple peaks.This measure of “center” is not often used in quantitative analyses, but is often helps provide a nice description.</p>
<p>When creating a histogram from a set of data, often the choice of binwidth will affect the modes of the graph. Consider the following graphs of <span class="math inline">\(n=200\)</span> data points, where we have slightly different binwidths.</p>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>With the two smaller binwidths, sample randomness between adjacent bins obscures the overall shape and we have many different modes. However the <em>larger</em> binwidth results in a histogram that more effectively communicates the shape of the distribution and has just a single mode at around 6000 seconds (= 100 minutes = 1 hour 40 minutes). When making histograms the choice of binwidth (or equivalently, the number of bins) should not be ignored and a balance should be struck between simplifying the data too much vs seeing too much of the noise resulting from the sample randomness.</p>
</div>
<div id="examples" class="section level3">
<h3><span class="header-section-number">1.4.4</span> Examples</h3>
<ul>
<li>Suppose a retired professor my father were to become bored and enroll into the the author’s STA 570 course, how would that affect the mean and median age of the STA 570 students?
<ul>
<li>The mean would move much more than the median. Suppose the class has 5 people right now, ages 21, 22, 23, 23, 24 and therefore the median is 23. When the retired professor joins, the ages will be 21, 22, 23, 23, 24, 72 and the median will remain 23. However, the mean would move because we add in such a large outlier. Whenever we are dealing with skewed data, the mean is pulled toward the outlying observations.</li>
</ul></li>
<li>In 2010 during a player’s strike in the NFL, the median NFL player salary was $770,000 while the mean salary was $1.9 million. Clearly the player’s union would talk about the median while the team owners preferred to talk about the mean. Why is there such a difference?
<ul>
<li>Because salary data contains outliers (e.g. superstar players with salaries in excess of 20 million) and the minimum salary for a rookie is $375,000. Financial data often reflects a highly skewed distribution and the median is often a better measure of centrality in these cases.</li>
</ul></li>
</ul>
</div>
</div>
<div id="measures-of-spread" class="section level2">
<h2><span class="header-section-number">1.5</span> Measures of Spread</h2>
<p>The second question to ask of a dataset is ‘How much spread is in the data?’ The fancier (and eventually more technical) word for spread is ‘variability’. As with centrality, there are several ways to measure this.</p>
<div id="range" class="section level3">
<h3><span class="header-section-number">1.5.1</span> Range</h3>
<p>Range is the distance from the largest to the smallest value in the dataset.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># max( TenMileRace$net ) - min( TenMileRace$net )</span>
TenMileRace <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">Range =</span> <span class="kw">max</span>(net) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(net) )</code></pre></div>
<pre><code>##   Range
## 1  7722</code></pre>
<p>In general, this method is highly sensitive to outlier observations and isn’t often used.</p>
</div>
<div id="inter-quartile-range" class="section level3">
<h3><span class="header-section-number">1.5.2</span> Inter-Quartile Range</h3>
<p>The p-th percentile is the observation (or observations) that has at most <span class="math inline">\(p\)</span> percent of the observations below it and <span class="math inline">\((1-p)\)</span> above it, where <span class="math inline">\(p\)</span> is between 0 and 100. The median is the <span class="math inline">\(50\)</span>th percentile. Often we are interested in splitting the data into four equal sections using the <span class="math inline">\(25\)</span>th, <span class="math inline">\(50\)</span>th, and <span class="math inline">\(75\)</span>th percentiles (which, because it splits the data into four sections, we often call these the <span class="math inline">\(1\)</span>st, <span class="math inline">\(2\)</span>nd, and <span class="math inline">\(3\)</span>rd quartiles).</p>
<p>In general we could be interested in dividing the data up into an arbitrary number of sections, and refer to those as quantiles of my data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">quantile</span>( TenMileRace<span class="op">$</span>net ) <span class="co"># gives the 5-number summary by default</span></code></pre></div>
<pre><code>##    0%   25%   50%   75%  100% 
##  2814  4950  5555  6169 10536</code></pre>
<p>The inter-quartile range (IQR) is defined as the distance from the <span class="math inline">\(3\)</span>rd quartile to the <span class="math inline">\(1\)</span>st.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># IQR( TenMileRace$net )</span>
TenMileRace <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">CalcIQR =</span> <span class="kw">IQR</span>(net) ) </code></pre></div>
<pre><code>##   CalcIQR
## 1    1219</code></pre>
<p>Notice that we’ve defined IQR before when we looked at box-and-whisker plots and this is exactly the length of the box part of a box-and-whisker plot.</p>
</div>
<div id="variance" class="section level3">
<h3><span class="header-section-number">1.5.3</span> Variance</h3>
<p>One way to measure the spread of a distribution is to ask “what is the typical distance of an observation to the mean?” We could define the <span class="math inline">\(i\)</span>th deviate as <span class="math display">\[e_{i}=x_{i}-\bar{x}\]</span> and then ask what is the average deviate? The problem with this approach is that the sum (and thus the average) of all deviates is always 0. <span class="math display">\[\sum_{i=1}^{n}(x_{i}-\bar{x}) =   \sum_{i=1}^{n}x_{i}-\sum_{i=1}^{n}\bar{x}
    =   n\frac{1}{n}\sum_{i=1}^{n}x_{i}-n\bar{x}
    =   n\bar{x}-n\bar{x}
    =   0\]</span></p>
<p>The big problem is that about half the deviates are negative and the others are positive. What we really care is the distance from the mean, not the sign. So we could either take the absolute value, or square it.</p>
<p>There are some really good theoretical reasons to chose the square option. Squared terms are easier to deal with compared to absolute values, but more importantly, the spread of the normal distribution is parameterized via squared distances from the mean. Because the normal distribution is so important, we’ve chosen to define the sample variance so it matches up with the natural spread parameter of the normal distribution. So we square the deviates and then find the average deviate size (approximately) and call that the sample variance. <span class="math display">\[s^{2}=\frac{1}{n-1}\sum_{i=1}^{n}\left(x_{i}-\bar{x}\right)^{2}\]</span> Why do we divide by <span class="math inline">\(n-1\)</span> instead of <span class="math inline">\(n\)</span>?</p>
<ol style="list-style-type: decimal">
<li>If we divide by <span class="math inline">\(n\)</span>, then on average, we would tend to underestimate the population variance <span class="math inline">\(\sigma^{2}\)</span>.</li>
<li>The reason is because we are using the same set of data to estimate <span class="math inline">\(\sigma^{2}\)</span> as we did to estimate the population mean (<span class="math inline">\(\mu\)</span>). If we could use<br />
<span class="math display">\[\frac{1}{n}\sum_{i=1}^{n}\left(x_{i}-\mu\right)^{2}\]</span> as the estimator, we would be fine. But because we have to replace <span class="math inline">\(\mu\)</span> with <span class="math inline">\(\bar{x}\)</span> we have to pay a price.</li>
<li>Because the estimation of <span class="math inline">\(\sigma^{2}\)</span> requires the estimation of one other quantity, and using using that quantity, you only need <span class="math inline">\(n-1\)</span> data points and can then figure out the last one, we have used one degree of freedom on estimating the mean and we need to adjust the formula accordingly.</li>
</ol>
<p>In later chapters we’ll give this quantity a different name, so we’ll introduce the necessary vocabulary here. Let <span class="math inline">\(e_{i}=x_{i}-\bar{x}\)</span> be the error left after fitting the sample mean. This is the deviation from the observed value to the “expected value” <span class="math inline">\(\bar{x}\)</span>. We can then define the Sum of Squared Error as <span class="math display">\[SSE=\sum_{i=1}^{n}e_{i}^{2}\]</span> and the Mean Squared Error as <span class="math display">\[MSE=\frac{SSE}{df}=\frac{SSE}{n-1}=s^{2}\]</span> where <span class="math inline">\(df=n-1\)</span> is the appropriate degrees of freedom.</p>
<p>Calculating the variance of our small sample of five observations <span class="math inline">\(\left\{ 3,6,4,8,2\right\}\)</span>, recall that the sample mean was <span class="math inline">\(\bar{x}=4.6\)</span></p>
<table style="width:68%;">
<colgroup>
<col width="11%" />
<col width="27%" />
<col width="29%" />
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\((x_i-\bar{x})\)</span></th>
<th><span class="math inline">\((x_i-\bar{x})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>3</p></td>
<td><pre><code>  -1.6</code></pre></td>
<td><p>2.56</p></td>
</tr>
<tr class="even">
<td><p>6</p></td>
<td><pre><code>   1.4</code></pre></td>
<td><p>1.96</p></td>
</tr>
<tr class="odd">
<td><p>4</p></td>
<td><pre><code>  -0.6</code></pre></td>
<td><p>0.36</p></td>
</tr>
<tr class="even">
<td><p>8</p></td>
<td><pre><code>   3.4</code></pre></td>
<td><p>11.56</p></td>
</tr>
<tr class="odd">
<td><p>2</p></td>
<td><pre><code>  -2.6</code></pre></td>
<td><p>6.76</p></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>SSE = 23.2</td>
</tr>
</tbody>
</table>
<p>and so the sample variance is <span class="math display">\[s^2 = \frac{SSE}{n-1} = \frac{23.2}{(n-1)} = \frac{23.2}{4}=5.8\]</span></p>
<p>Clearly this calculation would get very tedious to do by hand and computers will be much more accurate in these calculations. In R, the sample variance is easily calculated by the function <code>var()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ToyData &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">x=</span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">6</span>,<span class="dv">4</span>,<span class="dv">8</span>,<span class="dv">2</span>) )
<span class="co"># var( ToyData$x )</span>
ToyData <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">s2 =</span> <span class="kw">var</span>(x) )</code></pre></div>
<pre><code>##    s2
## 1 5.8</code></pre>
<p>For the larger TenMileRace data set, the variance is just as easily calculated.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># var( TenMileRace$net )</span>
TenMileRace <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">s2 =</span> <span class="kw">var</span>(net) )</code></pre></div>
<pre><code>##         s2
## 1 940233.5</code></pre>
</div>
<div id="standard-deviation" class="section level3">
<h3><span class="header-section-number">1.5.4</span> Standard Deviation</h3>
<p>The biggest problem with the sample variance statistic is that the units are in the original units-squared. That means if you are looking at data about car fuel efficiency, then the values would be in mpg<span class="math inline">\(^{2}\)</span> which are units that I can’t really understand. The solution is to take the positive square root, which we will call the sample standard deviation. <span class="math display">\[s=\sqrt{s^{2}}\]</span> But why do we take the jog through through variance? Mathematically the variance is more useful and most distributions (such as the normal) are defined by the variance term. Practically though, standard deviation is easier to think about.</p>
<p>The sample standard deviation is important enough for R to have a function <code>sd()</code> that will calculate it for you.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># sd( TenMileRace$net )</span>
TenMileRace <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">s =</span> <span class="kw">sd</span>(net) )</code></pre></div>
<pre><code>##          s
## 1 969.6564</code></pre>
</div>
<div id="coefficient-of-variation" class="section level3">
<h3><span class="header-section-number">1.5.5</span> Coefficient of Variation</h3>
<p>Suppose we had a group of animals and the sample standard deviation of the animals lengths was 15 cm. If the animals were elephants, you would be amazed at their uniformity in size, but if they were insects, you would be astounded at the variability. To account for that, the coefficient of variation takes the sample standard deviation and divides by the absolute value of the sample mean (to keep everything positive)</p>
<p><span class="math display">\[CV=\frac{s}{\vert\bar{x}\vert}\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">TenMileRace <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>( <span class="dt">s =</span> <span class="kw">sd</span>(net),
                           <span class="dt">xbar =</span> <span class="kw">mean</span>(net),
                           <span class="dt">cv =</span> s <span class="op">/</span><span class="st"> </span><span class="kw">abs</span>(xbar) )</code></pre></div>
<pre><code>##          s     xbar        cv
## 1 969.6564 5599.065 0.1731818</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Previously using dplyr notation didn&#39;t help too much, but if we wanted</span>
<span class="co"># to calculate the statistics separately for each sex, the dplyr solution</span>
<span class="co"># is MUCH easier.</span>
TenMileRace <span class="op">%&gt;%</span><span class="st">                     </span><span class="co"># Summarize the Ten Mile Race Data</span>
<span class="st">  </span><span class="kw">group_by</span>(sex) <span class="op">%&gt;%</span><span class="st">                 </span><span class="co"># Subsequent actions are done seperately </span>
<span class="st">  </span><span class="kw">summarise</span>( <span class="dt">xbar =</span> <span class="kw">mean</span>(net),      <span class="co">#    for each gender</span>
             <span class="dt">s    =</span> <span class="kw">sd</span>(net),        <span class="co">#</span>
             <span class="dt">cv   =</span> s <span class="op">/</span><span class="st"> </span><span class="kw">abs</span>(xbar) ) <span class="co"># Calculate three different summary stats</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   sex    xbar     s    cv
##   &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 F     5916.  902. 0.152
## 2 M     5281.  930. 0.176</code></pre>
</div>
<div id="empirical-rule-of-thumb" class="section level3">
<h3><span class="header-section-number">1.5.6</span> Empirical Rule of Thumb</h3>
<p>For any mound-shaped sample of data the following is a reasonable rule of thumb:</p>
<table>
<thead>
<tr class="header">
<th align="center">Interval</th>
<th align="center">Approximate percent of Measurements</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(\bar{x}\pm s\)</span></td>
<td align="center">68%</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(\bar{x}\pm 2s\)</span></td>
<td align="center">95%</td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(\bar{x}\pm 3s\)</span></td>
<td align="center">99.7%</td>
</tr>
</tbody>
</table>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
</div>
<div id="shape" class="section level2">
<h2><span class="header-section-number">1.6</span> Shape</h2>
<p>We want to be able to describe the shape of a distribution and this section introduces the standard vocabulary.</p>
<div id="symmetry" class="section level3">
<h3><span class="header-section-number">1.6.1</span> Symmetry</h3>
<p>A distribution is said to be symmetric if there is a point along the x-axis (which we’ll call <span class="math inline">\(\mu\)</span>) which acts as a mirror and <span class="math inline">\(f( -|x-\mu| ) = f( |x-\mu| )\)</span>. In the following graphs, the point of symmetry is marked with a red line. <img src="01_Data_Summary_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>A distribution that is not symmetric is said to be asymmetric.</p>
</div>
<div id="unimodal-or-multi-modal" class="section level3">
<h3><span class="header-section-number">1.6.2</span> Unimodal or Multi-modal</h3>
<p>Recall one measure of centrality was mode. If there is just a single mode, then we refer to the distribution as unimodal. If there is two or more we would refer to it as bimodal or multi-modal.</p>
</div>
<div id="skew" class="section level3">
<h3><span class="header-section-number">1.6.3</span> Skew</h3>
<p>If a distribution has a heavier tail on one side or the other, we refer to it as a <em>skewed</em> distribution and the direction of the skew is towards the heavier tail. Usually (but not always), an asymmetric is skewed.</p>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">1.7</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li><p>O&amp;L 3.21. The ratio of DDE (related to DDT) to PCB concentrations in bird eggs has been shown to have had a number of biological implications. The ratio is used as an indication of the movement of contamination through the food chain. The paper “The ratio of DDE to PCB concentrations in Great Lakes herring gull eggs and its us in interpreting contaminants data” reports the following ratios for eggs collected at 13 study sites from the five Great Lakes. The eggs were collected from both terrestrial and aquatic feeding birds.</p>
<table>
<colgroup>
<col width="21%" />
<col width="78%" />
</colgroup>
<tbody>
<tr class="odd">
<td><p>Source Type</p></td>
<td><p>DDE to PCB Ratio</p></td>
</tr>
<tr class="even">
<td><p><strong>Terrestrial</strong></p></td>
<td><p>76.50, 6.03, 3.51, 9.96, 4.24, 7.74, 9.54, 41.70, 1.84, 2.5, 1.54</p></td>
</tr>
<tr class="odd">
<td><p><strong>Aquatic</strong></p></td>
<td><p>0.27, 0.61, 0.54, 0.14, 0.63, 0.23, 0.56, 0.48, 0.16, 0.18</p></td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li>By hand, compute the mean and median separately for each type of feeder.</li>
<li>Using your results from part (a), comment on the relative sensitivity of the mean and median to extreme values in a data set.</li>
<li>Which measure, mean or median, would you recommend as the most appropriate measure of the DDE to PCB level for both types of feeders? Explain your answer.</li>
</ol></li>
<li><p>O&amp;L 3.31. Consumer Reports in its June 1998 issue reports on the typical daily room rate at six luxury and nine budget hotels. The room rates are given in the following table.</p>
<table>
<thead>
<tr class="header">
<th align="center">Hotel Type</th>
<th align="center">Nightly Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Luxury</td>
<td align="center">$175, $180, $120, $150, $120, $125</td>
</tr>
<tr class="even">
<td align="center">Budget</td>
<td align="center">$50, $50, $49, $45, $36, $45, $50, $50, $40</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-alpha">
<li>By hand, compute the means and standard deviations of the room rates for each class of hotel.</li>
<li>Give a practical reason why luxury hotels might have higher variability than the budget hotels. (Don’t just say the standard deviation is higher because there is more spread in the data, but rather think about the Hotel Industry and why you might see greater price variability for upscale goods compared to budget items.)</li>
</ol></li>
<li>Suppose that we have two groups of individuals, each with a mean value <span class="math inline">\(\bar{x}_i\)</span>. We wish to combine the two groups together and find the mean value for the combined group (denoted <span class="math inline">\(\bar{x}_c\)</span>).
<ol style="list-style-type: lower-alpha">
<li>Suppose <span class="math inline">\(n_1=1\)</span> and <span class="math inline">\(n_2=1\)</span> (i.e. there is one individual in each group) and the means of the two groups are <span class="math inline">\(\bar{x}_1 = 10\)</span> and <span class="math inline">\(\bar{x}_2=14\)</span>. What is the sum of the ages of individuals in the combined group? What is the mean age of the combined group?</li>
<li>Suppose that <span class="math inline">\(n_1=50\)</span>? What is the mean age of the combined group?</li>
<li>Finally suppose that <span class="math inline">\(n_2=75\)</span>. What is the mean age of the combined group?</li>
<li>Write a formula for the weighted average of the mean of the combined group as <span class="math display">\[\bar{x}_c = w_1 \bar{x}_1 + w_2 \bar{x}_2 = \sum_{i=1}^2 w_i \bar{x}_i\]</span> by defining the group <em>weighting factors</em> <span class="math inline">\(w_i\)</span>.</li>
<li>Explain why the weights represent the relative contribution to the overall mean for each group.</li>
</ol></li>
<li><p>Use R to confirm your calculations in problem 1 (the pollution data). Show the code you used and the subsequent output. It will often be convenient for me to give you code that generates a data frame instead of uploading an Excel file and having you read it in. The data can be generated using the following commands:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">PolutionRatios &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
  <span class="dt">Ratio =</span> <span class="kw">c</span>(<span class="fl">76.50</span>, <span class="fl">6.03</span>, <span class="fl">3.51</span>, <span class="fl">9.96</span>, <span class="fl">4.24</span>, <span class="fl">7.74</span>, <span class="fl">9.54</span>, <span class="fl">41.70</span>, <span class="fl">1.84</span>, <span class="fl">2.5</span>, <span class="fl">1.54</span>,
             <span class="fl">0.27</span>, <span class="fl">0.61</span>, <span class="fl">0.54</span>, <span class="fl">0.14</span>, <span class="fl">0.63</span>, <span class="fl">0.23</span>, <span class="fl">0.56</span>,  <span class="fl">0.48</span>, <span class="fl">0.16</span>, <span class="fl">0.18</span>       ),
  <span class="dt">Type  =</span> <span class="kw">c</span>( <span class="kw">rep</span>(<span class="st">&#39;Terrestrial&#39;</span>,<span class="dv">11</span>), <span class="kw">rep</span>(<span class="st">&#39;Aquatic&#39;</span>,<span class="dv">10</span>) ) )

<span class="co"># Print out some of the data to confirm what the column names are</span>
<span class="kw">head</span>( PolutionRatios )</code></pre></div>
<pre><code>##   Ratio        Type
## 1 76.50 Terrestrial
## 2  6.03 Terrestrial
## 3  3.51 Terrestrial
## 4  9.96 Terrestrial
## 5  4.24 Terrestrial
## 6  7.74 Terrestrial</code></pre>
<p><em>Hint: for computing the means and medians for each type of feeder separately, the <code>group_by()</code> command we demonstated earlier in the chapter is convenient.</em></p></li>
<li><p>Use R to confirm your calculations in problem 2 (the hotel data). Show the code you used and the subsequent output. The data can be loaded into a data frame using the following commands Show the code you used and the subsequent output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Hotels &lt;-<span class="st"> </span><span class="kw">data.frame</span>(
  <span class="dt">Price =</span> <span class="kw">c</span>(<span class="dv">175</span>, <span class="dv">180</span>, <span class="dv">120</span>, <span class="dv">150</span>, <span class="dv">120</span>, <span class="dv">125</span>, <span class="dv">50</span>, <span class="dv">50</span>, <span class="dv">49</span>, <span class="dv">45</span>, <span class="dv">36</span>, <span class="dv">45</span>, <span class="dv">50</span>, <span class="dv">50</span>, <span class="dv">40</span>),
  <span class="dt">Type  =</span> <span class="kw">c</span>( <span class="kw">rep</span>(<span class="st">&#39;Luxury&#39;</span>,<span class="dv">6</span>),  <span class="kw">rep</span>(<span class="st">&#39;Budget&#39;</span>, <span class="dv">9</span>) ) )

<span class="co"># Print out some of the data to confirm what the column names are</span>
<span class="kw">head</span>( Hotels )</code></pre></div>
<pre><code>##   Price   Type
## 1   175 Luxury
## 2   180 Luxury
## 3   120 Luxury
## 4   150 Luxury
## 5   120 Luxury
## 6   125 Luxury</code></pre></li>
<li><p>For the hotel data, create side-by-side box-and-whisker plots to compare the prices.</p></li>
<li><p>Match the following histograms to the appropriate boxplot.</p>
<p><img src="01_Data_Summary_files/figure-html/unnamed-chunk-27-1.png" width="672" /> <img src="01_Data_Summary_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<ol style="list-style-type: lower-alpha">
<li>Histogram A goes with boxplot __________</li>
<li>Histogram B goes with boxplot __________</li>
<li>Histogram C goes with boxplot __________</li>
<li>Histogram D goes with boxplot __________</li>
</ol></li>
<li><p>Twenty-five employees of a corporation have a mean salary of $62,000 and the sample standard deviation of those salaries is $15,000. If each employee receives a bonus of $1,000, does the standard deviation of the salaries change? Explain your reasoning.</p></li>
<li><p>Histograms of the salaries of two corporations. They have the same mean salary, but very different shapes. Use the shape of the distributions to justify which has a lower median salary.</p></li>
<li><p>The chemicals in clay used to make pottery can differ depending on the geographical region where the clay originated. Sometimes, archaeologists use a chemical analysis of clay to help identify where a piece of pottery originated. Such an analysis measures the amount of a chemical in the clay as a percent of the total weight of the piece of pottery. The boxplots below summarize analyses done for three chemicals—X, Y, and Z—on pieces of pottery that originated at one of three sites: I, II, or III.</p>
<img src="01_Data_Summary_files/figure-html/unnamed-chunk-29-1.png" width="672" />
<ol style="list-style-type: lower-alpha">
<li>For chemical Z, describe how the percents found in the pieces of pottery are similar and how they differ among the three sites.</li>
<li>Consider a piece of pottery known to have originated at one of the three sites, but the actual site is not known.
<ol style="list-style-type: lower-roman">
<li>Suppose an analysis of the clay reveals that the sum of the percents of the three chemicals X, Y, and Z is <span class="math inline">\(20.5\%\)</span>. Based on the boxplots, which site—I, II, or III—is the most likely site where the piece of pottery originated? Justify your choice.</li>
<li>Suppose only one chemical could be analyzed in the piece of pottery. Which chemical—X, Y, or Z— would be the most useful in identifying the site where the piece of pottery originated? Justify your choice.</li>
</ol></li>
</ol></li>
</ol>

</div>
</div>






<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>The oldest recorded age was that of a French women, Jeanne Calment, who lived to be to the age of 122 years.<a href="1-summary-statistics-and-graphing.html#fnref1">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"],
"instapper": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/dereksonderegger/570_II/raw/master/01_Data_Summary.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
